# Site settings
title: Ian's House
description: Ian lives here
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ian Warren
user_description: Exquisite Muji Singapore, the best Boeing 787 Gaggenau flat white sleepy Baggu discerning pintxos boulevard premium. Carefully curated perfect international punctual conversation sleepy.
user_title: Technical Game Designer

# Google Analytics
google-analytics:
  id: ""

# SASS/SCSS compilation
sass:
  sass_dir: _sass
  style: compressed

# Build exclusions
exclude:
  - package.json
  - node_modules
  - vendor
